### ISSUE TITLE
我拥有此域名 kubecdn.com 不知您是否有购买需求

### ISSUE THREAD

**Issue by aapelismith** [ilhaan/kubeCDN#1]
![image](https://user-images.githubusercontent.com/44763019/83356870-78ca3e80-a39b-11ea-8d50-01269039bbb2.png)

我拥有此域名 kubecdn.com 不知您是否有购买需求?

I own this domain name kubecdn.com, do you have purchase needs?

**Comment by ilhaan** [comment]
Nope
